### ISSUE TITLE
Not sure

### ISSUE THREAD

**Issue by jgefen** [JoshVarty/ProjectionBufferTutorial#3]
I have tried this solution to create a code editor but for some reason the keyboard events are not passing correctly to the editor text.
For example if I use the arrows it will behave like tab (passing between the text to the zoom in the bar)
also when I click on diagnostics or find results the cursor does not move to the position (or the scroll).
When I attach the VsCode directly using an Editor factory it works.

**Comment by JoshVarty** [comment]
Sorry for the slow response. It's very likely this approach doesn't work anymore. I originally created it for Visual Studio 2010 and made sure it worked up until Visual Studio 2013. It's likely they've changed VS internals in ways that make this approach not work anymore.
